### ISSUE TITLE
TSOA app compilation is slow

### ISSUE THREAD

**Issue by staycoolcall911** [winglang/setup-tsoa-hybrid#1]
The DX of working on this TSOA app suffers from slow compilation.
This is most likely due to the fact that each time we need to restart the TSOA service.

It hurts the most when:
1.  Hot reloading
2. Running tests

Here's how to reproduce:
1. Clone the repo locally: `git clone https://github.com/winglang/setup-tsoa-hybrid.git`
2. Run `npm i` on the project folder.
3. Then `wing run src/main.w`.
4. Modify code to see that reloading Wing Console takes 10 seconds.
    - More importantly modify the ts files (the tsoa source code is something that is usually changed)
    - modify `src/main.w` and save

**Comment by Chriscbr** [comment]
I threw in some extra logs to get an idea of where the time's being spent. A few things I noticed, out of the 10 second reload:

- It seems to take about 3-4 seconds between me saving my file and the simulator's `update()` method getting called. I'm not sure if this is due to the file watcher being slow, or some other performance issue. (cc @skyrpex)
- Around 1s is spent in total updating most of the other resources. Some of this could be parallelized with https://github.com/winglang/wing/issues/6151. These ones in particular take a few hundred ms to start:
  - root/Default/Services/imagesBucket/AwsConsoleField/Handler
  - root/Default/Services/imagesBucket/BucketArnField/Handler
  - root/Default/Services/imagesBucket/FileBrowser/delete
  - root/Default/Services/imagesBucket/FileBrowser/list
- The rest of the time (about 5-6s) is spent starting up root/Default/Service/Service_sim/Service (`tsoa.Service`).

**Comment by ekeren** [comment]
Updated issue description to put more emphasis on changing the ts files (the tsoa source code)

**Comment by ekeren** [comment]
The emphasis here should be optimizing the time spent when the tsoa related source code change. 

Keep in mind that this is how currently developers are working locally, they change the code and almost instantly (for the time it takes for the tsoa to compile) they are able to test the code. 

Maybe we can optimize this flow somehow

**Comment by staycoolcall911** [comment]
@ekeren - do we know how they implemented hot reloading of the TSOA service? We can probably implement the same battle-tested mechanism they've been using

**Comment by ekeren** [comment]
> @ekeren - do we know how they implemented hot reloading of the TSOA service? We can probably implement the same battle-tested mechanism they've been using

Good question, using [nodemon](https://nodemon.io/) (see TSOA doc https://tsoa-community.github.io/docs/live-reloading.html) is a lot quicker then our current solution. 

Anyhow, I'll ask

**Comment by ekeren** [comment]
I've talked with the team that is working on this. They don't have a unified way of doing hot reloading. 

They are using esbuild to bundle stuff together and then using nodemon

**Comment by eladcon** [comment]
i think we can start with watching the TS files in the service and not restarting the simulator for those changes

**Comment by ekeren** [comment]
> i think we can start with watching the TS files in the service and not restarting the simulator for those changes

Keep in mind that you will need to refresh the service httpClient based on any changes in openapi aspec

**Comment by ekeren** [comment]
@eladcon have added the option to watch a specific folder for TSOA. 
If I use this change, it requires some folder moving around but the result is good enough. 

I'll post a video of the experience later today

**Comment by ekeren** [comment]
The watch is a good enough solution, closing
